//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transactions_in_EF_Example
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int AddressID { get; set; }
        public string AddressText { get; set; }
        public Nullable<int> TownID { get; set; }
    
        public virtual Town Town { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
